### PR TITLE
added rounded corners

### PR DESCRIPTION
**Pull request by dhruv-porwal**
Added rounded corners to button for better design

## Describe your changes 
added rounded corners
Please include a summary of the changes and the related issue. Why is this change required? What problem does it solve? 
made interface look better
Fixes # (issue)

# Checklist: 
- [x] I have performed a self-review of my code 
- [x] I have commented my code
- [x] My changes generate no new warnings 
- [x] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by yellowHatpro** [comment]
@dhruv-porwal, thanks for showing interest in the project. However, the app is currently being actively developed under PWoC. You can register there, add issues, and then get them assigned to work on them. I won't be closing the PRs; you can register through this site: http://pwoc.vercel.app/ and join the discord server for further communication.
Happy coding!

**Comment by dhruv-porwal** [comment]
I am already registered sir
Kindly nark these prs as PWOC

**Comment by yellowHatpro** [comment]
In that case, can you make an issue? I saw you made 2 PRs for rounded corners that can be marked as a single issue. To avoid such cases, issues come in handy. Also, you can communicate in the discord server regarding issues, so everything is clear later.

**Comment by dhruv-porwal** [comment]
Sure, will do that.
Sorry for inconvenience.

**Pull request merged**
