### PR TITLE
Updated README.md

### LINKED ISSUE #22: Improve README
Add badges for tech used 
Add contributors list
Add any more stuff that would look nice

### PR DESCRIPTION
**Pull request by umarfarooq478**
Added Contributors Name

## Describe your changes 
I have added the contributor's list as required
Fixes #22 

# Checklist: 
- [ Yes ] I have performed a self-review of my code 
- [ Yes ] I have commented my code
- [ Yes ] My changes generate no new warnings 
- [ Yes ] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by yellowHatpro** [comment]
@umarfarooq478 are you still working on this issue?

**Comment by umarfarooq478** [comment]
No, I updated this once

**Comment by yellowHatpro** [comment]
@umarfarooq478 can you make the required changes? I'll merge the PR soon after that.

**Comment by umarfarooq478** [comment]
Sure

**Pull request closed without merging**
