### PR TITLE
#16 add an issue template

### PR DESCRIPTION
**Pull request by abhinavmalhotra01**
Added an issue template

## Changes 
I have added an issue template for the repository 

# (issue)
Added the template

# Checklist: 
- [ ✔️] I have performed a self-review of my code 
- [ ✔️] I have commented my code
- [ ✔️] My changes generate no new warnings 
- [ ✔️] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Comment by abhinavmalhotra01** [comment]
Let me know of any required changes 😊

**Comment by yellowHatpro** [comment]
@abhinavmalhotra01 Thanks for the work. This looks clean, but we need to create two different templates since issues can be either feature requests or bug reports. 
You can take help from https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms . If you run into any problem, you can ping me.

**Comment by abhinavmalhotra01** [comment]
Ohk sir , will work on this

**Comment by abhinavmalhotra01** [comment]
sir kindly review the updated files

**Comment by yellowHatpro** [comment]
lgtm, thanks for the work 💯

**Comment by abhinavmalhotra01** [comment]
thanks 😊

**Pull request merged**
